// <auto-generated />
namespace FBVLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration003));
        
        string IMigrationMetadata.Id
        {
            get { return "201706042257035_migration003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
